#!/usr/bin/env python2.7

import sys

def main(argv):

    infile = open(argv[1], 'r')
    outfile = open(argv[2], 'w')

    for line in infile:
        for x in xrange(len(line)):
            if line[x] != '0':
                outfile.write(line[x])


if __name__ == "__main__":
    main(sys.argv)
